import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";


export const poppins  = Poppins({
  weight:['200','300','400','500'],
  variable: "--font-poppins",
  subsets: ['latin'],
  style: ['normal', 'italic']




})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased bg-neutral-950 text-white pb-[10000px]`}
      >
       
        {children}
      </body>
    </html>
  );
}
